version: '3.8'
services:
  api:
    build: ./back
    container_name: backend_c
    ports:
      - '8000:8000'
  front:
    build: ./front/myapp
    container_name: frontend_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true