# Generated by Django 4.0.5 on 2022-06-29 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineCompany',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'AirlineCompanies',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('address', models.TextField()),
                ('phone_number', models.TextField(unique=True)),
                ('credit_card_number', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('landing_time', models.DateTimeField()),
                ('remaining_tickets', models.IntegerField()),
                ('airline_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.airlinecompany')),
                ('destination_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_country', to='base.country')),
                ('origin_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_country', to='base.country')),
            ],
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user_role')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.flight')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.AddField(
            model_name='airlinecompany',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.country'),
        ),
        migrations.AddField(
            model_name='airlinecompany',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
    ]
