# Generated by Django 4.0.5 on 2022-08-08 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_alter_airlinecompany_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credit_card_number',
            field=models.CharField(default='', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.user_role'),
        ),
    ]
