# Generated by Django 4.0.5 on 2022-08-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_flight_airline_company_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirlineCompany',
        ),
    ]
