# Generated by Django 4.0.5 on 2022-08-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_profile_credit_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(default='placeholder', upload_to='static/'),
        ),
    ]
