# Generated by Django 4.0.5 on 2022-08-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_country_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(default='static/placeholder.png', upload_to='static'),
        ),
    ]
